// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Item struct {
	Classid    int64
	Itemname   string
	Daychange  float64
	Weekchange float64
	Imageurl   string
}

type Price struct {
	Pricedate time.Time
	ItemID    int64
	Price     float64
}
